server:
  port: 8081

spring:
  config:
    activate:
      on-profile: default

  rsocket:
    server:
      port: 7001
      transport: tcp
      mapping-path: /rsocket

    user:
      client:
        host: ${EVENT_HOST:localhost}
        port: ${EVENT_PORT:7002}
    notification:
      client:
        host: ${EVENT_HOST:localhost}
        port: ${EVENT_PORT:7005}
    duration: 10
    attempts: 3

  r2dbc:
    url: r2dbc:mariadb://localhost:3306/alf
    username: admin
    password: admin
    pool:
      max-size: 10
      max-create-connection-time: 10s
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  timeInMinutes: 30


---

spring:
  config:
    activate:
      on-profile: test

  rsocket:
    server:
      port: 7002
      transport: tcp
      mapping-path: /rsocket

    user:
      client:
        host: ${EVENT_HOST:localhost}
        port: ${EVENT_PORT:7002}
    notification:
      client:
        host: ${EVENT_HOST:localhost}
        port: ${EVENT_PORT:7005}
    duration: 10
    attempts: 3

  r2dbc:
    url: r2dbc:tc:mariadb://localhost:3306/alf
    username: root
    password: root
    pool:
      max-size: 10
      max-create-connection-time: 10s
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  timeInMinutes: 30
