server:
  port: 8082

spring:
  config:
    activate:
      on-profile: default

  rsocket:
    server:
      port: 7002
      transport: tcp
      mapping-path: /rsocket

    event:
      client:
        host: ${EVENT_HOST:localhost}
        port: ${EVENT_PORT:7001}
    duration: 10
    attempts: 3

org:
  neo4j:
    driver:
      neo4j_host: ${NEO4J_HOST:localhost}
      uri: bolt://${org.neo4j.driver.neo4j_host}:7687
      pool:
        connection-acquisition-timeout: 10m



---

spring:
  config:
    activate:
      on-profile: test

  rsocket:
    server:
      port: 7002
      transport: tcp
      mapping-path: /rsocket

    event:
      client:
        host: ${EVENT_HOST:localhost}
        port: ${EVENT_PORT:7001}
    duration: 10
    attempts: 3

org:
  neo4j:
    driver:
      neo4j_host: ${NEO4J_HOST:localhost}
      uri: bolt://${org.neo4j.driver.neo4j_host}:7687
      authentication:
        username: neo4j
        password: test
      pool:
        connection-acquisition-timeout: 10m
