version: '3.5'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "alf"
    ports:
      - "3306:3306"
    volumes:
      - "./alf.sql:/docker-entrypoint-initdb.d/1.sql"  
