server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default

  rsocket:
    server:
      port: 7000
      transport: tcp
      mapping-path: /rsocket

    event:
      client:
        host: ${EVENT_HOST:localhost}
        port: ${EVENT_PORT:7001}
    user:
      client:
        host: ${EVENT_HOST:localhost}
        port: ${EVENT_PORT:7002}
    duration: 10
    attempts: 3

org:
  neo4j:
    driver:
      neo4j_host: ${NEO4J_HOST:localhost}
      uri: bolt://${org.neo4j.driver.neo4j_host}:7687
      pool:
        connection-acquisition-timeout: 10m

resilience4j.ratelimiter:
  instances:
    alf:
      limitForPeriod: 10
      limitRefreshPeriod: 5s
      timeoutDuration: 33s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
